### ISSUE TITLE
Issue when parsing URLs

### ISSUE THREAD

**Issue by NullDivision** [Kreozot/callback-loader#2]
When parsing URLs with `callback-loader`

```
const BASE_URL = urlParse({development: 'http://localhost:8000/'});
```

I get an error `Module build failed: SyntaxError: Unexpected token h`

A bit of digging around i found out that the parsed result was `{ "development": ""http":\/\/"localhost":8000\/" }` originating from the replace function on line 49 of `callback-loader.js`.

**Comment by Kreozot** [comment]
Can you please show me the code of your callback function?

**Comment by NullDivision** [comment]
Sure

webpack.config.babel.js

```
configCallback: {
    urlParse: (urls) => {
      const ENV = process.env.NODE_ENV || 'development';

      return urls.hasOwnProperty(ENV) ? urls[ENV] : urls.development;
    }
  }
```

**Comment by NullDivision** [comment]
Since then I've changed it to parse a separate file and separated protocol, domain and port but I really don't see the use for the replacement of `[A-z]+`.

Or at least have a less restricted match set.

**Comment by Kreozot** [comment]
I guess the problem is in quotes. Remember that your function return JS-code - not quoted string. In your case the result will be this: 

``` javascript
const BASE_URL = http://localhost:8000/;
```

So this is invalid code. You must add quotes in your return statement:

``` javascript
return `"${urls.hasOwnProperty(ENV) ? urls[ENV] : urls.development}"`;
```

In this case your result will be this:

``` javascript
const BASE_URL = "http://localhost:8000/";
```

**Comment by NullDivision** [comment]
I told you what the output is. The matcher you integrated in the callback
is /[A-z]+/ which means that it breaks at the colon. I know what you're
saying and that's not it. try it yourself.

**Comment by Kreozot** [comment]
Ok, I got it. Thank you! The fix will be soon.

**Comment by Kreozot** [comment]
Fixed. Thank you!
